<?php

return [
    'mainTable' => 'activity_user_prizes',
    'matchInfo' => [
        'activity_report_cash_vouchers' => [8, 9, 12, 13, 14],
        'activity_report_register_10s' => [18],
        'activity_report_real_object_prizes' => [1, 2, 3, 4, 6, 7],
        'activity_report_withdrawals' => [19],
        'activity_report_player_stats' => 'all',
    ],
    'matchInfoUpdate' => [
        'activity_report_rebate_vouchers' => [11],
        'activity_report_deposit_1times' => [16],
        'activity_report_deposit_4times' => [17],
    ],
    'reportTables' => [
        'activity_report_player_stats' => [
            'field' => [
                'username',
                'count_cash_voucher',
                'count_real_object',
                'prize_total_price',
                'count_lottery',
                'deposit_total_amount',
                'activity_total_turnover',
                'activity_total_profits',
                'player_contributions',
                'register_at',
                'parent',
                'user_type_formatted',
                'created_at',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'count_cash_voucher' => 'integer',
                'count_real_object' => 'integer',
                'prize_total_price' => 'decimal:10,2',
                'count_lottery' => 'integer',
                'deposit_total_amount' => 'decimal:10,2',
                'activity_total_turnover' => 'decimal:10,2',
                'activity_total_profits' => 'decimal:10,2',
                'player_contributions' => 'decimal:10,2',
                'register_at' => 'timestamp',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
            ],
            'convertField' => [
                'count_cash_voucher' => [8, 9, 12, 13, 14, 18],
                'count_real_object' => [1, 2, 3, 4, 6, 7],
                'prize_total_price' => 'prize_total_price',
                'count_lottery' => [15],
                'deposit_total_amount' => 'deposit_total_amount',
                'activity_total_turnover' => 'activity_total_turnover',
                'activity_total_profits' => 'activity_total_profits',
                'player_contributions' => 'player_contributions',
                'register_at' => 'user',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_register_10s' => [
            'field' => [
                'username',
                'register_at',
//                'activated_at',
                'lock_time',
                'register_ip',
                'parent',
                'user_type_formatted',
                'created_at',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'register_at' => 'timestamp',
//                'activated_at' => 'timestamp',
                'lock_time' => 'timestamp',
                'register_ip' => 'string:15',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
            ],
            'convertField' => [
                'register_at' => 'user',
//                'activated_at' => 'user',
                'lock_time' => 'bank_card',
                'register_ip' => 'user',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_deposit_4times' => [
            'field' => [
                'username',
                'real_amount',
                'cash_bank_weekly',
                'first_week',
                'second_week',
                'third_week',
                'fourth_week',
                'fifth_week',
                'sixth_week',
                'seventh_week',
//                'remote_ip',
                'parent',
                'user_type_formatted',
                'created_at',
                'prize_id',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'real_amount' => 'decimal:10,2',
                'cash_bank_weekly' => 'decimal:10,2',
                'first_week' => 'string:20',
                'second_week' => 'string:20',
                'third_week' => 'string:20',
                'fourth_week' => 'string:20',
                'fifth_week' => 'string:20',
                'sixth_week' => 'string:20',
                'seventh_week' => 'string:20',
                'parent' => 'string:16',
//                'remote_ip' => 'string:15',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
                'prize_id' => 'integer',
            ],
            'convertField' => [
                'real_amount' => 'deposit',
                'cash_bank_weekly' => 'calculate_cash_weekly',
                'first_week' => 'activity_stat_help',
                'second_week' => 'activity_stat_help',
                'third_week' => 'activity_stat_help',
                'fourth_week' => 'activity_stat_help',
                'fifth_week' => 'activity_stat_help',
                'sixth_week' => 'activity_stat_help',
                'seventh_week' => 'activity_stat_help',
                'deposit_time' => 'deposit.pay_time',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_deposit_1times' => [
            'field' => [
                'username',
                'real_amount',
                'deposit_total_turnover',
                'turnover_32times_at',
                'parent',
                'user_type_formatted',
                'created_at',
                'prize_id',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'real_amount' => 'decimal:10,2',
                'deposit_total_turnover' => 'decimal:10,2',
                'turnover_32times_at' => 'timestamp',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
                'prize_id' => 'integer',
            ],
            'convertField' => [
                'real_amount' => 'deposit',
                'deposit_total_turnover' => 'calculate_deposit_total_turnover',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
                'turnover_32times_at' => 'activity_stat_help',
            ],
        ],
        'activity_report_withdrawals' => [
            'field' => [
                'username',
                'transaction_amount',
//                'withdrawal_ip',
                'parent',
                'user_type_formatted',
                'created_at',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'transaction_amount' => 'decimal:10,2',
//                'withdrawal_ip' => 'string:15',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
            ],
            'convertField' => [
                'transaction_amount' => 'withdrawal',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_rebate_vouchers' => [
            'field' => [
                'username',
                'prize_name',
                'created_at',
                'remote_ip',
                'turnover_48h',
                'rebate_amount',
                'parent',
                'user_type_formatted',
                'prize_id',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'prize_name' => 'string:50',
                'remote_ip' => 'string:15',
                'turnover_48h' => 'decimal:10,2',
                'rebate_amount' => 'decimal:10,2',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
                'prize_id' => 'integer',
            ],
            'convertField' => [
                'turnover_48h' => 'turnover_48h',
                'rebate_amount' => 'calculate_turnover_48h',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_cash_vouchers' => [
            'field' => [
                'username',
                'prize_name',
                'remote_ip',
                'parent',
                'user_type_formatted',
                'created_at',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'prize_name' => 'string:50',
                'remote_ip' => 'string:15',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
            ],
            'convertField' => [
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
        'activity_report_real_object_prizes' => [
            'field' => [
                'username',
                'prize_name',
                'remote_ip',
                'value',
                'activity_turnover',
                'parent',
                'user_type_formatted',
                'created_at',
            ],
            'fieldType' => [
                'username' => 'string:16',
                'prize_name' => 'string:50',
                'remote_ip' => 'string:15',
                'value' => 'decimal:10,2',
                'activity_turnover' => 'decimal:12,2',
                'parent' => 'string:16',
                'user_type_formatted' => 'string:20',
                'created_at' => 'timestamp',
            ],
            'convertField' => [
                'value' => 'activity_prize',
                'activity_turnover' => 'activity_turnover',
                'parent' => 'user',
                'user_type_formatted' => 'parent_user',
            ],
        ],
    ],
];
